name:                measure-ghc
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/haddock-perf#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web

extra-source-files:
- README.md

default-extensions:
- LambdaCase
- ViewPatterns
- RecordWildCards
- TupleSections
- DeriveGeneric
- PartialTypeSignatures
- DeriveFunctor
- TypeApplications
- ParallelListComp
- MultiWayIf

data-files:
- data/*

dependencies:
  base

library:
  source-dirs: lib
  dependencies:
  - lens
  - text
  - directory
  - filepath
  - containers
  - bifunctors
  - optparse-applicative
  - attoparsec
  - safe-exceptions
  - sqlite-simple
  - sqlite-extension-functions
  - direct-sqlite
  - cassava
  - bytestring
  - ansi-wl-pprint
  - MemoTrie
  - mtl
  - vector
  - terminal-size
  - errors
  - transformers
  - reflection
  other-modules:
  - Paths_measure_ghc
executables:
  measure-ghc:
    source-dirs:      src
    main:             Main.hs
    dependencies:
    - measure-ghc
    - base
