resolver: nightly-2017-08-15
compiler: ghc-8.3.20170813
compiler-check: newer-minor
packages:
- .
- sqlite-extension-functions
- stackage-curator
- location: foundation
  extra-dep: true
- location:
    git: https://github.com/fpco/store
    commit: 07f6a2bea50ba1b7aee9fda46b2006119fbe390f
  extra-dep: true
- generic-lens-labels

extra-deps:
- newtype-generics-0.5
# - lens-4.15.3
# - optparse-applicative-0.14.0.0
# - direct-sqlite-2.3.20
- MemoTrie-0.6.8
# - vector-0.12.0.1
- cryptohash-conduit-0.1.1
- store-0.4.3.1
- store-core-0.4.1
- th-utilities-0.2.0.1
- directory-1.3.1.1
- generic-lens-0.4.0.0

allow-newer: true

docker:
  enable: true
  image: measure-ghc
  stack-exe: host
